/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioWaterArt: typeof import('./src/components/AudioWaterArt.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    DateFormat: typeof import('./src/components/DateFormat.vue')['default']
    HeaderLink: typeof import('./src/components/HeaderLink.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    MonacoEditorDemo: typeof import('./src/components/MonacoEditorDemo.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostArchive: typeof import('./src/components/PostArchive.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
