/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccumulateDemo: typeof import('./src/components/demo/AccumulateDemo.vue')['default']
    AdditiveDemo: typeof import('./src/components/demo/AdditiveDemo.vue')['default']
    AnimateMotionDemo: typeof import('./src/components/demo/AnimateMotionDemo.vue')['default']
    BezierCurveOneDemo: typeof import('./src/components/demo/BezierCurveOneDemo.vue')['default']
    CalcModeDemo: typeof import('./src/components/demo/CalcModeDemo.vue')['default']
    ClipboardDemo: typeof import('./src/components/demo/ClipboardDemo.vue')['default']
    DateFormat: typeof import('./src/components/DateFormat.vue')['default']
    DraggableDemo: typeof import('./src/components/demo/DraggableDemo.vue')['default']
    FeBelndDemo: typeof import('./src/components/demo/FeBelndDemo.vue')['default']
    FeColorMatrixDemo: typeof import('./src/components/demo/FeColorMatrixDemo.vue')['default']
    FeComponentTransferDemo: typeof import('./src/components/demo/FeComponentTransferDemo.vue')['default']
    FeCompositeDemo: typeof import('./src/components/demo/FeCompositeDemo.vue')['default']
    FeConvolveMatrixDemo: typeof import('./src/components/demo/FeConvolveMatrixDemo.vue')['default']
    FeDisplacementMapDemo: typeof import('./src/components/demo/FeDisplacementMapDemo.vue')['default']
    FeMorphologyDemo: typeof import('./src/components/demo/FeMorphologyDemo.vue')['default']
    FeTurbulenceDemo: typeof import('./src/components/demo/FeTurbulenceDemo.vue')['default']
    FileUploadDemo: typeof import('./src/components/demo/FileUploadDemo.vue')['default']
    GeolocationDemo: typeof import('./src/components/demo/GeolocationDemo.vue')['default']
    HeaderLink: typeof import('./src/components/HeaderLink.vue')['default']
    IntersectionObserver: typeof import('./src/components/demo/IntersectionObserver.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    LeafletMapDemo: typeof import('./src/components/demo/LeafletMapDemo.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MutationObserver: typeof import('./src/components/demo/MutationObserver.vue')['default']
    PointArt: typeof import('./src/components/art/PointArt.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostArchive: typeof import('./src/components/PostArchive.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    ResizeObserver: typeof import('./src/components/demo/ResizeObserver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
