# 构建命令
[build]
command = "pnpm run build"
publish = "dist"

# 设置生产环境的变量
[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_FLAGS = "--version"
NODE_VERSION = "22.16.0" # Node.js 版本
PNPM_VERSION = "10.6.5" # pnpm 版本
COREPACK_ENABLE = "1"
