packages: []
catalogs:
  prod:
    '@vueuse/core': ^13.0.0
    date-fns: ^4.1.0
    feed: ^4.2.2
    gsap: ^3.12.7
    leaflet: ^1.9.4
    nprogress: ^0.2.0
    p5i: ^0.6.0
    spark-md5: ^3.0.2
    vue: ^3.5.13
    vue-router: ^4.5.0
    vue-router-better-scroller: ^0.0.0
  # dev: []
  # build: []
  # test: []
  # types: []
