/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/archive': RouteRecordInfo<'/archive', '/archive', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/buy-monitor-guide': RouteRecordInfo<'/blog/buy-monitor-guide', '/blog/buy-monitor-guide', Record<never, never>, Record<never, never>>,
    '/blog/css-border-image': RouteRecordInfo<'/blog/css-border-image', '/blog/css-border-image', Record<never, never>, Record<never, never>>,
    '/blog/css-houdini-api': RouteRecordInfo<'/blog/css-houdini-api', '/blog/css-houdini-api', Record<never, never>, Record<never, never>>,
    '/blog/css-text-ellipsis': RouteRecordInfo<'/blog/css-text-ellipsis', '/blog/css-text-ellipsis', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-decorator': RouteRecordInfo<'/blog/design-pattern-decorator', '/blog/design-pattern-decorator', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-factory': RouteRecordInfo<'/blog/design-pattern-factory', '/blog/design-pattern-factory', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-observer': RouteRecordInfo<'/blog/design-pattern-observer', '/blog/design-pattern-observer', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-strategy': RouteRecordInfo<'/blog/design-pattern-strategy', '/blog/design-pattern-strategy', Record<never, never>, Record<never, never>>,
    '/blog/github-actions': RouteRecordInfo<'/blog/github-actions', '/blog/github-actions', Record<never, never>, Record<never, never>>,
    '/blog/javascript-style-guide': RouteRecordInfo<'/blog/javascript-style-guide', '/blog/javascript-style-guide', Record<never, never>, Record<never, never>>,
    '/blog/jetpack-compose-state-and-recomposition': RouteRecordInfo<'/blog/jetpack-compose-state-and-recomposition', '/blog/jetpack-compose-state-and-recomposition', Record<never, never>, Record<never, never>>,
    '/blog/js-arraybuffer': RouteRecordInfo<'/blog/js-arraybuffer', '/blog/js-arraybuffer', Record<never, never>, Record<never, never>>,
    '/blog/js-file-upload': RouteRecordInfo<'/blog/js-file-upload', '/blog/js-file-upload', Record<never, never>, Record<never, never>>,
    '/blog/js-proxy': RouteRecordInfo<'/blog/js-proxy', '/blog/js-proxy', Record<never, never>, Record<never, never>>,
    '/blog/js-reflect': RouteRecordInfo<'/blog/js-reflect', '/blog/js-reflect', Record<never, never>, Record<never, never>>,
    '/blog/markdown-grammer': RouteRecordInfo<'/blog/markdown-grammer', '/blog/markdown-grammer', Record<never, never>, Record<never, never>>,
    '/blog/vue3-reactivity': RouteRecordInfo<'/blog/vue3-reactivity', '/blog/vue3-reactivity', Record<never, never>, Record<never, never>>,
    '/blog/vue3-reactivity-part1': RouteRecordInfo<'/blog/vue3-reactivity-part1', '/blog/vue3-reactivity-part1', Record<never, never>, Record<never, never>>,
    '/blog/web-api-clipboard': RouteRecordInfo<'/blog/web-api-clipboard', '/blog/web-api-clipboard', Record<never, never>, Record<never, never>>,
    '/blog/web-api-draggable': RouteRecordInfo<'/blog/web-api-draggable', '/blog/web-api-draggable', Record<never, never>, Record<never, never>>,
    '/blog/web-api-file': RouteRecordInfo<'/blog/web-api-file', '/blog/web-api-file', Record<never, never>, Record<never, never>>,
    '/blog/web-api-geolocation': RouteRecordInfo<'/blog/web-api-geolocation', '/blog/web-api-geolocation', Record<never, never>, Record<never, never>>,
    '/blog/web-api-indexedDB': RouteRecordInfo<'/blog/web-api-indexedDB', '/blog/web-api-indexedDB', Record<never, never>, Record<never, never>>,
    '/blog/web-api-observer': RouteRecordInfo<'/blog/web-api-observer', '/blog/web-api-observer', Record<never, never>, Record<never, never>>,
    '/blog/web-api-storage': RouteRecordInfo<'/blog/web-api-storage', '/blog/web-api-storage', Record<never, never>, Record<never, never>>,
    '/blog/web-api-worker': RouteRecordInfo<'/blog/web-api-worker', '/blog/web-api-worker', Record<never, never>, Record<never, never>>,
    '/blog/what-is-BFC': RouteRecordInfo<'/blog/what-is-BFC', '/blog/what-is-BFC', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/basic-concepts-of-networking': RouteRecordInfo<'/notes/basic-concepts-of-networking', '/notes/basic-concepts-of-networking', Record<never, never>, Record<never, never>>,
    '/notes/cors': RouteRecordInfo<'/notes/cors', '/notes/cors', Record<never, never>, Record<never, never>>,
    '/notes/css-mask': RouteRecordInfo<'/notes/css-mask', '/notes/css-mask', Record<never, never>, Record<never, never>>,
    '/notes/learn-git': RouteRecordInfo<'/notes/learn-git', '/notes/learn-git', Record<never, never>, Record<never, never>>,
    '/notes/moblie-status-bar-style': RouteRecordInfo<'/notes/moblie-status-bar-style', '/notes/moblie-status-bar-style', Record<never, never>, Record<never, never>>,
    '/notes/package-json': RouteRecordInfo<'/notes/package-json', '/notes/package-json', Record<never, never>, Record<never, never>>,
    '/notes/read-Professional-JavaScript-for-Web-Developers-4th-1-chapter': RouteRecordInfo<'/notes/read-Professional-JavaScript-for-Web-Developers-4th-1-chapter', '/notes/read-Professional-JavaScript-for-Web-Developers-4th-1-chapter', Record<never, never>, Record<never, never>>,
    '/notes/request': RouteRecordInfo<'/notes/request', '/notes/request', Record<never, never>, Record<never, never>>,
    '/notes/request-headers': RouteRecordInfo<'/notes/request-headers', '/notes/request-headers', Record<never, never>, Record<never, never>>,
    '/notes/response': RouteRecordInfo<'/notes/response', '/notes/response', Record<never, never>, Record<never, never>>,
    '/notes/response-headers': RouteRecordInfo<'/notes/response-headers', '/notes/response-headers', Record<never, never>, Record<never, never>>,
    '/notes/svg-animate': RouteRecordInfo<'/notes/svg-animate', '/notes/svg-animate', Record<never, never>, Record<never, never>>,
    '/notes/svg-base-graphics': RouteRecordInfo<'/notes/svg-base-graphics', '/notes/svg-base-graphics', Record<never, never>, Record<never, never>>,
    '/notes/svg-clip-path': RouteRecordInfo<'/notes/svg-clip-path', '/notes/svg-clip-path', Record<never, never>, Record<never, never>>,
    '/notes/svg-fill': RouteRecordInfo<'/notes/svg-fill', '/notes/svg-fill', Record<never, never>, Record<never, never>>,
    '/notes/svg-filter': RouteRecordInfo<'/notes/svg-filter', '/notes/svg-filter', Record<never, never>, Record<never, never>>,
    '/notes/svg-gradient': RouteRecordInfo<'/notes/svg-gradient', '/notes/svg-gradient', Record<never, never>, Record<never, never>>,
    '/notes/svg-image': RouteRecordInfo<'/notes/svg-image', '/notes/svg-image', Record<never, never>, Record<never, never>>,
    '/notes/svg-mask': RouteRecordInfo<'/notes/svg-mask', '/notes/svg-mask', Record<never, never>, Record<never, never>>,
    '/notes/svg-other-tag': RouteRecordInfo<'/notes/svg-other-tag', '/notes/svg-other-tag', Record<never, never>, Record<never, never>>,
    '/notes/svg-path': RouteRecordInfo<'/notes/svg-path', '/notes/svg-path', Record<never, never>, Record<never, never>>,
    '/notes/svg-pattern-fiil-and-stroke': RouteRecordInfo<'/notes/svg-pattern-fiil-and-stroke', '/notes/svg-pattern-fiil-and-stroke', Record<never, never>, Record<never, never>>,
    '/notes/svg-stroke': RouteRecordInfo<'/notes/svg-stroke', '/notes/svg-stroke', Record<never, never>, Record<never, never>>,
    '/notes/svg-text-tag-and-property': RouteRecordInfo<'/notes/svg-text-tag-and-property', '/notes/svg-text-tag-and-property', Record<never, never>, Record<never, never>>,
    '/six/': RouteRecordInfo<'/six/', '/six', Record<never, never>, Record<never, never>>,
    '/six/2024-12-23': RouteRecordInfo<'/six/2024-12-23', '/six/2024-12-23', Record<never, never>, Record<never, never>>,
    '/six/2024-12-24': RouteRecordInfo<'/six/2024-12-24', '/six/2024-12-24', Record<never, never>, Record<never, never>>,
    '/six/2024-12-25': RouteRecordInfo<'/six/2024-12-25', '/six/2024-12-25', Record<never, never>, Record<never, never>>,
    '/six/2024-12-26': RouteRecordInfo<'/six/2024-12-26', '/six/2024-12-26', Record<never, never>, Record<never, never>>,
    '/six/2024-12-27': RouteRecordInfo<'/six/2024-12-27', '/six/2024-12-27', Record<never, never>, Record<never, never>>,
    '/six/2024-12-31': RouteRecordInfo<'/six/2024-12-31', '/six/2024-12-31', Record<never, never>, Record<never, never>>,
    '/six/2025-01-11': RouteRecordInfo<'/six/2025-01-11', '/six/2025-01-11', Record<never, never>, Record<never, never>>,
    '/tag/[tag]': RouteRecordInfo<'/tag/[tag]', '/tag/:tag', { tag: ParamValue<true> }, { tag: ParamValue<false> }>,
    '/tags': RouteRecordInfo<'/tags', '/tags', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }
}
