/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/archive': RouteRecordInfo<'/archive', '/archive', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-decorator': RouteRecordInfo<'/blog/design-pattern-decorator', '/blog/design-pattern-decorator', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-factory': RouteRecordInfo<'/blog/design-pattern-factory', '/blog/design-pattern-factory', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-observer': RouteRecordInfo<'/blog/design-pattern-observer', '/blog/design-pattern-observer', Record<never, never>, Record<never, never>>,
    '/blog/design-pattern-strategy': RouteRecordInfo<'/blog/design-pattern-strategy', '/blog/design-pattern-strategy', Record<never, never>, Record<never, never>>,
    '/blog/markdown-grammer': RouteRecordInfo<'/blog/markdown-grammer', '/blog/markdown-grammer', Record<never, never>, Record<never, never>>,
    '/blog/monaco-editor': RouteRecordInfo<'/blog/monaco-editor', '/blog/monaco-editor', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/moblie-status-bar-style': RouteRecordInfo<'/notes/moblie-status-bar-style', '/notes/moblie-status-bar-style', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/tags/[tag]': RouteRecordInfo<'/tags/[tag]', '/tags/:tag', { tag: ParamValue<true> }, { tag: ParamValue<false> }>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }
}
